config/routes.rb
Rails.application.routes.draw do
    resources :blurays, :renters, :rentals
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bluray.rb
class Bluray < ApplicationRecord
    has_many :rentals
    has_many :renters, through: :rental
end

app/models/rental.rb
class Rental < ApplicationRecord
    belongs_to :bluray
    belongs_to :renter

    def rental_info
        self.name
    end
end

app/models/renter.rb
class Renter < ApplicationRecord
  has_many :rentals
  has_many :blurays, through: :rental

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email_address, presence: true, uniqueness: true
    validates :phone, presence: true
    validates :creditc, presence: true, uniqueness: true



    def full_name
        self.first_name + " " + self.last_name
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blurays_controller.rb
class BluraysController < ApplicationController
    before_action :find_bluray, only: [:show, :edit, :update, :destroy]

    def index
        @blurays = Bluray.all
    end

    def show
    end

    def new
        @bluray = Bluray.new
    end

    def create
        @bluray = Bluray.create(bluray_params)
        redirect_to bluray_path(@bluray)
    end

    def edit
    end

    def update
        @bluray.update(bluray_params)
        @bluray.save
        redirect_to bluray_path(@bluray)
    end

    def destroy
        @bluray.destroy
        flash[:notice] = "Bluray Deleted"
        redirect_to blurays_path
    end

    private

    def find_bluray
        @bluray = Bluray.find(params[:id])
    end

    def bluray_params
        params.require(:bluray).permit(:title, :actor, :year, :genre, :director)
    end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
    before_action :find_rental, only: [:show, :edit, :update, :destroy]

    def index
        @rentals = Rental.all
    end

    def show
    end

    def new
        @rental = Rental.new
    end

    def create
        @rental = Rental.find_or_create_by(rental_params)    
        redirect_to rental_path(@rental)
    end

    def edit
    end

    def update
        @rental.update(rental_params)
        @rental.save
        redirect_to rental_path(@rental)
    end

    def destroy
        @rental.destroy
        redirect_to rentals_path
    end

    private

    def find_rental
        @rental = Rental.find(params[:id])
    end

    def rental_params
        params.require(:rental).permit(:name, :renter_id, :bluray_id)
    end
end

app/controllers/renters_controller.rb
class RentersController < ApplicationController
    before_action :find_renter, only: [:show, :edit, :update, :destroy]



  def new

    @renter = Renter.new

  end

  def create
    @renter = Renter.create(renter_params)
    if @renter.valid?
      @renter.save
      redirect_to renter_path(@renter)
    else
      render :new
    end
  end

  def edit


  end

  def update

    @renter.update(renter_params)
    @renter.save
    redirect_to renter_path(@renter)

  end

  def destroy

    @renter.destroy
    flash[:notice] = "Renter Deleted"
    redirect_to renters_path

  end


private


    def find_renter
        @renter = Renter.find(params[:id])
    end

    def renter_params
        params.require(:renter).permit(:first_name, :last_name, :email_address, :phone, :creditc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blurays_helper.rb
module BluraysHelper
end

app/helpers/renters_helper.rb
module RentersHelper
end

app/views/blurays/_form.html.erb
<%= form_for @bluray do |f| %>
    <%= f.label :title, "Title:" %>
    <%= f.text_field :title %><br>

    <%= f.label :actor, "Actor:" %>
    <%= f.text_field :actor %><br>
    
    <%= f.label :year, "Year:" %>
    <%= f.text_field :year %><br>
    
    <%= f.label :genre, "genre" %>
    <%= f.text_field :genre %><br>
    
    <%= f.label :director, "director:" %>
    <%= f.text_field :director %><br>
    
    <%= f.submit %>
<% end %>

app/views/blurays/edit.html.erb
<h1>Edit Bluray</h1>

<%= render "form" %>

app/views/blurays/index.html.erb
<h1>Available Blurays</h1>

<ul>
    <% @blurays.each do |bluray| %>
        <li> <%= link_to bluray.title, bluray_path(bluray) %> </li>
    <% end %>
</ul>

<%= link_to "Create a Bluray", new_bluray_path %>

app/views/blurays/new.html.erb
<h1>New Bluray</h1>

<%= render "form" %>

app/views/blurays/show.html.erb
<h1><%= @bluray.title %> <%= @bluray.year %></h1>

<h2>Title: <%= @bluray.title %></h2>
<h2>Actor: <%= @bluray.actor %></h2>
<h2>Year: <%= @bluray.year %></h2>
<h2>Genre: <%= @bluray.genre %></h2>
<h2>Director:  <%= @bluray.director %></h2>

<%= link_to "Edit this Bluray", edit_bluray_path(@bluray) %>

<%= link_to "All Bluray", blurays_path %>
<br><br>

<%= form_tag @bluray, method: "DELETE" do %>
    <%= submit_tag "Delete" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IronBox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= flash[:notice] %>
    
    <%= yield %>
  </body>
</html>

app/views/rentals/_form.html.erb
<%= form_for @rental  do |f| %>
    <h3><%= f.label :name, "Name:"%>
    <%= f.text_field :name %></h3>

    <h3><%= f.label :renter_id %>
    <%= f.collection_select(:renter_id, Renter.all, :id, :full_name, {:prompt => 'Choose a Renter'}) %></h3>

    <h3><%= f.label :bluray_id %>
    <%= f.collection_select(:bluray_id, Bluray.all, :id, :title, {:prompt => 'Choose a Title'}) %></h3>
   
    <%= f.submit "Add" %></h3>
<% end %>

app/views/rentals/edit.html.erb
<h1>Edit <%= @rental.name%></h1>

<%= render "form" %>

app/views/rentals/index.html.erb
<h1>These are the Rentals</h1>

<ul>
    <% @rentals.each do |rental| %>
        <li> <%= link_to rental.rental_info, rental_path(rental) %> </li>
    <% end %>
</ul>

app/views/rentals/new.html.erb
<h1>Create Rental</h1>

<%= render "form" %>

app/views/rentals/show.html.erb
<h1>Rental Detail for <%= @rental.name %> Rental </h1>

<p>Name: <%= @rental.name %></p>
<p>Renter: <%= @rental.renter.full_name %></p>
<p>Bluray: <%= @rental.bluray.title %></p>

app/views/renters/_form.html.erb
<%= form_for @renter do |f| %>
    <%= f.label :first_name, "First Name: " %>
    <%= f.text_field :first_name %><br>
    
    <%= f.label :last_name, "Last Name: " %>
    <%= f.text_field :last_name %><br>
    
    <%= f.label :email_address, "Email: " %>
    <%= f.text_field :email_address %><br>
    
    <%= f.label :phone, "Phone: " %>
    <%= f.text_field :phone %><br>
    
    <%= f.label :creditc, "CC Number: " %>
    <%= f.text_field :creditc %><br>
    
    <%= f.submit %>
<% end %>

app/views/renters/edit.html.erb
<h1>Edit Renter</h1>

<%= render "form" %>

app/views/renters/index.html.erb
<h1>These are the Renters</h1>

<ul>
  <% @renters.each do |renter| %>
  <li> <%= link_to renter.full_name, renter_path(renter) %> </li>
  <% end %>
</ul>

app/views/renters/new.html.erb
<h1>New Renter</h1>


<%= render partial: "shared/errors_list", locals: {object: @renter} %>

<%= render "form" %>

app/views/renters/show.html.erb
<h1>Renter</h1>

<p>First Name: <%= @renter.first_name %></p>
<p>Last Name: <%= @renter.last_name %></p>
<p>Email: <%= @renter.email_address %></p>
<p>Phone: <%= @renter.phone %></p>

<%= link_to "Update this Renter", edit_renter_path(@renter) %>

<%= link_to "Delete This Renter", renter_path(@renter), method: :delete %>

app/views/shared/_errors_list.html.erb
<% if object.errors %>
    <ul class="error-list">
        <% object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %> 